// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPY6aWEbXfgriQ3DUMGLgTF5YL5TZzfHk',
    appId: '1:501773014975:web:4e782b37d558002154f30a',
    messagingSenderId: '501773014975',
    projectId: 'taskapp-4e28c',
    authDomain: 'taskapp-4e28c.firebaseapp.com',
    storageBucket: 'taskapp-4e28c.firebasestorage.app',
    measurementId: 'G-2XLWSQS9J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt7nKg2CV4h1mFoKPR1u2KScpRBwqiSvk',
    appId: '1:501773014975:android:7a21aaf30ab16b5f54f30a',
    messagingSenderId: '501773014975',
    projectId: 'taskapp-4e28c',
    storageBucket: 'taskapp-4e28c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIpP-W_2kUGqKu65FagvDm_gTd1ieflJs',
    appId: '1:501773014975:ios:bdeb430eb6f4dcb554f30a',
    messagingSenderId: '501773014975',
    projectId: 'taskapp-4e28c',
    storageBucket: 'taskapp-4e28c.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIpP-W_2kUGqKu65FagvDm_gTd1ieflJs',
    appId: '1:501773014975:ios:bdeb430eb6f4dcb554f30a',
    messagingSenderId: '501773014975',
    projectId: 'taskapp-4e28c',
    storageBucket: 'taskapp-4e28c.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkDa8JLuz8XQmLTBxvASRT6vivyeexpoM',
    appId: '1:501773014975:web:9ee1bf38b0f5ffb654f30a',
    messagingSenderId: '501773014975',
    projectId: 'taskapp-4e28c',
    authDomain: 'taskapp-4e28c.firebaseapp.com',
    storageBucket: 'taskapp-4e28c.firebasestorage.app',
    measurementId: 'G-MLC33MJSQ8',
  );
}
